print("What is the name of the gift giver?")
giver = raw_input()
print("What is the present that was given?")
present = raw_input()
print("how old were you on your birthday?")
age = int(raw_input())
print("What is your name?")
name = raw_input()
print("")
print("Dear "+ giver +",")
print("")
print("Thank you for the "+present)
print("I really like it. I can't believe")
print("I am already "+ str(age) +" years old")
print("it does not feel much different than being " +str(age-1)+"\n")
print("Sincerely,\n")
print(name)
